apiVersion: apps/v1   
kind: Deployment    
metadata:            
  name: book-deployment    
  labels:        
    app: book    
spec:            
  replicas: 1    
  selector:       
    matchLabels: 
      app: book
  template:        
    metadata:    
      labels:    
        app: book
    spec:        
      containers:    
      - name: book
        image: motomark/test   
        ports:
          - containerPort: 443 
---
apiVersion: v1
kind: Service
metadata:
  name: book-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: book
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30001